### ISSUE TITLE
Unkown Exception but Plugin works...

### ISSUE THREAD

**Issue by Zerriss** [DreiMu/ServerStarter#2]
Hello, can you say me, how I fix this please?

[12:13:20 ERROR]: Couldn't pass PlayerChooseInitialServerEvent to serverstarter
java.lang.NullPointerException: Cannot invoke "com.moandjiezana.toml.Toml.getString(String)" because the return value of "com.moandjiezana.toml.Toml.getTable(String)" is null
        at de.dreimu.minecraft.velocity.serverstarter.Main.onServerChooseEvent(Main.java:262) ~[?:?]
        at de.dreimu.minecraft.velocity.serverstarter.Lmbda$20.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

Sorry for my English... I'm german xd

**Comment by Zerriss** [comment]
Okay nevermind. I now what it was... now it works xd
